services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - postgres
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin 
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80
    networks:
      - postgres
    restart: unless-stopped

  api:
    image: node:16
    restart: unless-stopped
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: "npm start"
    ports:
      - 3000:3000

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: